apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-y03r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-y03r
    app.kubernetes.io/part-of: cin4s-839-0046-app
  name: devfile-sample-y03r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-y03r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-y03r
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0046-tenant/cin4s-839-0046-app/devfile-sample-y03r@sha256:3ce297038b3d2d7bb2a04613dbae464df96517fb2c8df6e24686d164c1d70336
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
